[package]
name = "bezier-surface"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = {version = "0.32.3", default-features = false, features = ["default_fonts", "x11", "wayland", "glow"]}
image = "0.25.8"
rfd = "0.15.4"
